### PR TITLE
Implemented find_pheromone_target-method & tests (Issue 83, 88)

### PR DESCRIPTION
**Pull request by tis22**
In general the `find_pheromone_target`-method returns the index of the field from the pheromones-array with the highest pheromone level.
The `step_size` can be used to set the range in which the pheromone levels are evaluated.

If there is no field with a highest value, a random field is chosen from those available within the `step_size`.
This happens in different ways (refer to the comments in the code).

The method always returns an index of a new position (x, y) for the ant.

I took particular care to ensure that this method also works correctly at the critical points (corners and edges).

Furthermore I have also already implemented the associated tests, as this requires a clear understanding of the different types of errors.

<del>Please note that the code must be carefully merged with the current state of the code.</del>

### CODE REVIEW

**Comment by Jonah-gr** [comment]
Great work :), but I think it would be advantageous if the grid did not depend on the step_size but on a parameter that the user can set later via the GUI. The default value should probably be 1, because the size of the grid depends on the size of the map and is freely adjustable by the user anyway. But in any case, the grid must be significantly smaller than the map, otherwise the performance would suffer too much.

It would be great if you could adjust this! If you have any questions or notes just leave a comment.

**Comment by tis22** [comment]
I don't fully understand what you mean by your comment, I think you misinterpreted the code / parts of it.

>  if the grid did not depend on the step_size

The grid does not depend on the `step_size`.
The `step_size` is the parameter the user can set via the GUI by changing the colony's settings (at the moment in the main-code the `step_size`-default there is 3(?)). I agree with you that the default-`step_size` should be set to be 1, if we don't want to use the step_size in the `find_pheromone_target`-method at all, it can always be considered as 1.

Furthermore in the implementation of the `find_pheromone_target`-method the grid is not used.
The `find_pheromone_target`-method only uses the already existing `pheromone_array` and gives out an index of the next field the ant should move to.

As I mentioned in the issue this index has to be mapped to the original coordinates (center of the field) by another method (@AlhaririAnas will implement this method).
<br>

> But in any case, the grid must be significantly smaller than the map, otherwise the performance would suffer too much.

This was already implemented with the mapping-method (not this pull request).
<br>
For the **tests** I had to create an Grid to test the `find_pheromone_target`-method otherwise without an dummy-grid the tests would not be possible.
<br>
If you still see possible problems  and want to make changes after this comment, please mark them in the code for me and explain them in more detail again.

**Comment by AlhaririAnas** [comment]
Here's a method that finds the center of a pheromone field. @tis22 You can add it to the Simulation class and use it for testing your method.

```python
    def calculate_pheromone_target_pos(self, idx_target_pheromone_value, colony):
        
        n_row = colony.pheromone.pheromone_array.shape[1] #y
        n_col = colony.pheromone.pheromone_array.shape[2] #x        
        
        width_board = self.bounds[1] - self.bounds[0]
        height_board = self.bounds[3] - self.bounds[2]
        
        width_spot = width_board/ n_col
        height_spot = height_board/ n_row
        
        x_target_pos = idx_target_pheromone_value[1] * width_spot + width_spot/2 
        y_target_pos = idx_target_pheromone_value[0] * height_spot + height_spot/2
        
        return x_target_pos, -y_target_pos
```

If it serves its purpose, could you please create a GIF of it and upload it so we can see how it works :)

**Comment by tis22** [comment]
In order to fully make the simulation work, we first have to discuss how exactly we should include this method and what we should change in the `ant.move()`-method or the simulation.py.

Currently `ant.move()` takes a step in a random direction in the first epoch (= 0).
Then the simulation.py changes the further direction and position (randomly) in each subsequent epoch (`ant.move()` else condition).

Something needs to be fundamentally changed here, as we no longer want to randomly determine the position using `ant.move()` and the else statement if pheromones are found, but rather use the `find_pheromone_target`-method.

I guess if we want to do this, the mapping method would first have to be called (as we have the current (old) position of the ant).
Then if epoch = 0 a random step or if epoch > 0 `find_pheromone_target`-method would have to be applied and then `calculate_pheromone_target_pos`-method to get the actual position.

Since this are major changes and only indirectly belongs to the marked issues on this pull request I would recommend putting this in a new issue and closing this pull-request.
If changes need to be made to the `find_pheromone_target`-method, these can be made as part of the new issue.

**Comment by tis22** [comment]
Since one of you thought of this logic/issue it would be better if you also propose your ideas and implement the new methods according to your ideas.

**Comment by Jonah-gr** [comment]
I was thinking more of something like that:
1. we have a function `find_pheromone_target`, e.g. the respective Ant object or simply its coordinates and pheromone_status is passed. This function then returns the direction from the ant's coordnates to the center of the pheromone field with the highest expression. 
`pheromone_direction = pheromone_coordniates - ant_coordinates`
Of course, all variables must be a vector, i.e. a numpy array and only the pheromone grid that matches the pheromone_status is considered. If no matching pheromone field was found, the function returns (0, 0) (vector).
2. this function is called in Ant.move():
```python
def move(self, angle_offset=0):

        position = np.array(self.coordinates)
        
        if self.epoch == 0:
            theta = np.random.uniform(0, 2 * np.pi)
            z = np.random.uniform(-1, 1)
            
            x = np.sqrt(1 - z**2) * np.cos(theta)
            y = np.sqrt(1 - z**2) * np.sin(theta)
            
            self.direction = np.array([x, y]) * self.step_size

        else:
            
            if angle_offset == 0:
                angle_offset = np.random.uniform(-np.pi/4, np.pi/4)
                
            rotation_matrix = np.array([[np.cos(angle_offset), -np.sin(angle_offset)],
                                    [np.sin(angle_offset), np.cos(angle_offset)]])
            
            self.direction = np.dot(rotation_matrix, self.direction)
            pheromone_direction = self.colony.pherome.find_pheromone_target(self.coordinates, self.pheromone_status)
            self.direction = self.direction + pheromone_direction
            self.direction = self.direction / np.linalg.norm(self.direction) * self.step_size 
        
        future_position = position + self.direction
        self.epoch += 1
        return tuple(future_position)
```
 Of course, this only works if the ant class has self.colony as an attribute. However, you can simply add this when initializing the ants.
This makes the ants more likely to run in the direction of the pheromone trail that interests them. The ants should **not** run exactly to the pheromone trails, but there should still be a random factor. 

What do you think? Feel free to write criticism or comments.

**Pull request closed without merging**
