### PR TITLE
Issue 133 food collision and move

### PR DESCRIPTION
**Pull request by honnigmelone**
So I was working on this issue and came up with some solutions. Although when i try to implement them and run the GUI nothing happens. Normally I would continue and try longer until it works but the deadline is very close and im still feeling quite sick. So it would be nice if you could look over the implementations so far. 

I added a method check_food_collision_with_obstacles() to check whether one of the 4 corners of a food object is colliding with an obstacle. Returning true if it does, false if not. I guess pretty self explanatory.

Then I added a method relocate_object() to relocate the object in 1 of 4 directions and if it works it should change the foods coordinates accordingly. Because a food has 4 corners i thought it necessary to make a new adjust_food_position_in_bounds() that checks if the object is in bounds rather than only the bottom left coordinate. A temporary food object with the new position is created (which should not be shown in the gui). its checked whether it's in bounds and not colliding. If that is the case it should change the original foods coordinates to the new ones. If all 4 position dont work a random logic can be implemented but that makes no sense if the rest does not work properly.
Also tell me if this makes sense haha

### CODE REVIEW

**Comment by AlhaririAnas** [comment]
The problem was that adjust_food_position_within_bounds() returns an array, but food.coordinates expects a tuple. Now, there's a new issue: The food source moves multiple times instead of just once (see GIF). I'm working on solving this. But overall, good job, Nikita.

```python
                ....
                idx_row, idx_col = self.map_ant_coordinates_to_pheromone_index(ant_coordinates = ant.coordinates,
                                                                               colony = colony)
                
                colony.pheromone.leave_pheromone(pos = (idx_row, idx_col),
                                                 pheromone_status = ant.pheromone_status)    

            colony.pheromone.reduce_pheromones(reduce_fac, 0.001)
            
        for food in active_food_objects:
            self.check_food_collision_with_obstacles(food)
            self.relocate_object(food)
```

Aufzeichnung2024-02-22161228-ezgif com-video-to-gif-converter

**Comment by AlhaririAnas** [comment]
Okay, the loop was the problem; it was unnecessary. The calls now occur within `add_food()`.

The workflow test is returning an error, and I'm not sure why.


Aufzeichnung2024-02-22164530-ezgif com-video-to-gif-converter

**Comment by honnigmelone** [comment]
Hey Anas thanks for helping and finishing it off 😄 I already encountered the test problem aswell. It's the test for add_colony_and_food that does not work. I think it is because right now we assert a string and I think through the addition of relocate food now a food object should be created rather than a string.

**Comment by honnigmelone** [comment]
So i fixed the test and made it universal. With that i could not create a universal temporary object so that i try to work with the size and coordinates of the object directly. I am not sure if it's the datatype again or something different but nothing happens in my gui. Maybe you can have a quick look over it again 😢

**Comment by AlhaririAnas** [comment]
Unfortunately there are incorrect positioning of the objects (food source & colony). Can you try to take care of it please!

Aufzeichnung2024-02-22211729-ezgif com-video-to-gif-converter

**Comment by honnigmelone** [comment]
Ok it's a weird because in my gui the object are still not moving. Did you change anything locally? Because in your simulation they move?
But that they only move with collision should not be a problem.

**Comment by honnigmelone** [comment]
Like this?

**Comment by AlhaririAnas** [comment]
No, I haven't changed anything locally. Now it works that the food source is not placed overlapping with the obstacle, but not the other way around!

Aufzeichnung2024-02-22214445-ezgif com-video-to-gif-converter

**Comment by honnigmelone** [comment]
Now i added the logic also to add_obstacle(). Does it work now? I still can't test it 😿

**Review by AlhaririAnas — APPROVED** [review]
everything works as it should. Great job :)

**Pull request merged**
