### PR TITLE
added the tests for simulation class

### PR DESCRIPTION
**Pull request by heyitsalina**
hey guys! 😎
i added the tests for the simulation class, these are:
- test_check_future_position()
- test_map_ant_coordinates_to_pheromone_index()
- test_find_pheromone_trace()
- test_get_pheromone_position()
- test_create_statistic()

however, i came upon an error for the test_create_statistics() method which i can't really resolve 😪
here's the error message:
Bildschirmfoto 2024-02-19 um 11 48 40

i suppose it has something to do with the path file but i can't quite understand why.
maybe one of you has an idea and can lend a helping hand ? :)

### CODE REVIEW

**Comment by AlhaririAnas** [comment]
The error message occurs because the data cannot be loaded immediately after starting a study. Restarting the GUI is necessary, after which the data can be loaded.

**Comment by heyitsalina** [comment]
ooooh i see what you mean, i'll try in a minute to see if it works

**Comment by heyitsalina** [comment]
as far as i can understand, it still doesn't seem to work when restarting the gui for me :,,(

**Comment by Jonah-gr** [comment]
1. when testing whether the json file has been created, you may have to wait a little after calling `sim.create_statistic()`, because it may take a little time for it to be created.

2. the error dialog you see there refers to when you select "load data". So you would have to create a new study with "new study" first, then restart the gui before you select "load data".

If none of this helps, it could be because you are using macos. You should first check whether there really is a json file in the `statistics` folder after you have created a new study.

 I hope I could help you :)

**Comment by heyitsalina** [comment]
okay so the first two things didn't work out, the error message keeps popping up
what confuses me more tho, is the fact that when i look at the statistics folder there are new files from the new studies (i think, since the time stamps align with when i tried to make the tests work), however they are .tex files instead of a json file :,,) ? 

Bildschirmfoto 2024-02-19 um 20 41 08

**Comment by Jonah-gr** [comment]
In fact, the program should open the .json and not the .tex file. But if you have a .tex file, the json must also exist, I think.
Please check this:
- in `ant_search_algorithm/statistics` there is `statistics.json`.
- in `ant_search_algorithm/statistics/[time when folder was created]` there is `statistics.tex`.
- the code of this `statistics.tex` should look something like this: 
```Latex

    \documentclass{article}
    \usepackage{hyperref}
    \usepackage{tikz}
    \usepackage{pgfplots}
    \begin{document}

    \title{Ant Search Statistics}
    \author{\url{https://github.com/heyitsalina/ant_search_algorithm}}
    \maketitle

    \section{General Information}

    Epochs: 114\newline
Boundaries: [0, 720, -480, 0]


    \section{Colonies}

    \subsection*{Colony 1}
\begin{itemize}
\item Amount: 100
\item Coordinates: [119.7, -192.901]
\item Pheromone Grid: [12, 18]
\item Color: [0, 0, 0, 1]
\item Food Count: 4
\item Step Size: 3
\item Amount to Carry: 1
\item Search Radius: 3
\item Pheromone Influence: 0.01
\end{itemize}


    \section{Food}

    \subsection*{Food 1}
\begin{itemize}
\item Start amount: 100
\item Amount of food: 88
\item Coordinates: [251.734, -200.409]
\end{itemize}


    \section{Obstacles}

    \subsection*{Obstacle 1}
\begin{itemize}
\item Coordinates: [125.19468688964844, -375.11126708984375]
\item Size: [50.0, 50.0]
\end{itemize}


    \section{Overview}

    \begin{tikzpicture}
    \begin{axis}[xmin=0, xmax=720, ymin=-480, ymax=0, width=12cm, height=7cm, legend pos=outer north east, legend image post style={scale=0.5}]

    \addplot[only marks, mark=triangle, mark size=8pt, blue] coordinates {
    (169.7,-142.901)
    };
    \addlegendentry{Colony}

    \addplot[only marks, mark=*, mark size=8pt, red] coordinates {
    (301.73400000000004,-150.409)
    };
    \addlegendentry{Food}

    \addplot[only marks, mark=square, mark size=8pt, black] coordinates {
    (150.19468688964844,-350.11126708984375)
    };
    \addlegendentry{Obstacle}

    \end{axis}
    \end{tikzpicture}

    \end{document}
    
```

image
image

**Comment by heyitsalina** [comment]
okay i just looked at everything you mentioned @Jonah-gr and everything seems to be the way it has to be 🥲
yet still it keep saying that the json file does not exist even tho it's right there in the statistics folder with the same data as the .tex file 🥸

**Comment by heyitsalina** [comment]
a little update: @honnigmelone is so kind and is helping to solve the problem right now, it seems that he might have found a solution to my original error but has to debug some other errors that came along  

i'll still try your suggestions later as well, just to make sure everyting works accordingly 😅 !

**Comment by honnigmelone** [comment]
So i switched to @heyitsalina branch for the issue and changed it directly. It was a path problem. When the test_create_statistics() was executed, the working directory changed as well and went deeper into the statistics file:
screen_ant_path_problem

I then cut off the tail so that it should work with all users and shouldn't cause any problems with different users having different local paths. 
Then i adjusted the test settings for the tests to pass. I have not looked into whether those are the assertions/settings we aim for, so feel free to change that. But for now, that should do. Let me know if there is something wrong or if there are questions :) 
Hope the headaches and confusions are over 😢

**Comment by heyitsalina** [comment]
THANK YOU SO MUCH!!!

about the adjusted settings thing: i think every test file we created in our repo has different parameters set - as long as one test run works, i suppose it gives us a good coverage of the overall test cases :)

**Comment by Jonah-gr** [comment]
Great job!
But you @heyitsalina are still not able to load the settings in the gui again?

**Comment by heyitsalina** [comment]
@Jonah-gr 

Just tried it, this is what happens:
1. When trying your suggested step 1 to 4, it doesn`t work and still shows the same "No File Found" Error as before
2. However, adding the test.py file in the statistics folder and then executing python `./statistics/test.py` works perfectly and doesn't cause any issues 

I also just noticed that even with nikitas alterations, calling the test function still doesn't work for me 💀

**Review by honnigmelone — APPROVED** [review]

**Comment by honnigmelone** [comment]
Alina I think you're problem is not connected to the creation of the additional test you added to the simulation.py. That's why I would merge the changes now:)

**Pull request merged**
