### PR TITLE
added the test for colony method

### PR DESCRIPTION
**Pull request by heyitsalina**
i added a test file for our add_ants method in the colony class
however, i came upon an assertion error that i think is being caused by the method itself in the colony class. 
i tried to debug but couldn't really find a solution to my problem, maybe someone has ideas as to how i can fix the error? 
thanks :)

edit: regarding the assertion error, line 12 in test_colony.py file

### CODE REVIEW

**Comment by Jonah-gr** [comment]
Good job:) 
I have modified the code a bit by now immediately checking if there are exactly colony.amount many ants in the colony. Notice that the add_ants() method is executed directly when the colony object is initialized. Then the list of ants is emptied and the method is executed manually with new values.
All tests are now passed.

**Review by honnigmelone — APPROVED** [review]
Looks good :)
But I have a question, is there a reason why we hardcode the offset of the coordinates? (in colony and food class) Wouldn't it be better to also define the offset as a variable?

**Comment by Jonah-gr** [comment]
Do you mean this line @honnigmelone:
`assert ant.coordinates == (colony.coordinates[0] + 50, colony.coordinates[1] + 50)`?
The `+50` comes from the fact that the image for the colonies is 100x100 pixels in size and the coordinates of the colonies must be in the bottom left corner of the image. However, for the ants to appear in the center of the image, their coordinates must be extended by half the size of the image in both directions. These extensions depend on the size of the image of the colonies. You could of course replace the `+50` with `+colony.size[0]/2`, but at the moment the size is not taken into account in the gui.

**Comment by honnigmelone** [comment]
Hey @Jonah-gr, thanks for the detailed reply :) Yes, i mean that line.
I understand what you mean. I meant to just put it as a variable like `colony_offset= 50 ` and then `+ colony_offset`. This would just be for readability purposes and would not be that important for now. I wanted to mention it already 😄

**Pull request merged**
