### PR TITLE
Bounds of walking area of the ants

### PR DESCRIPTION
**Pull request by AlhaririAnas**
I added the check_bounds_area method in the Simulation class to make sure the ants don't go beyond the canvas borders. When the window size is changed using the 'Size' button, this is automatically detected, and the ants' boundaries dynamically adjust to the new size.

When the canvas is zoomed out, it's hard to see exactly where the boundaries are. That's why I added the draw_bounds method in the SimulationWidget class to visually show the boundaries with a rectangle that has black edges.

However, there's a small problem: Sometimes the ants cross the boundaries before changing their direction to be back within the boundaries. This is especially noticeable when the Step_size is set large, like 15.

ezgif com-video-to-gif-converted(2)

This is a minor problem that doesn't affect the functionality of the simulation. I will think about how to solve this problem. Your suggestions can help! But for now, this branch can be merged with the main if there are no other comments.

### CODE REVIEW

**Comment by AlhaririAnas** [comment]
The problem was that the move() method in the Ant class directly overwrote the Ant.coordinates attribute, causing the check to occur only after the ant moved to the next position. The solution involved changing the structure of the move() method. Instead of directly overwriting the Ant.coordinates attribute, the method now returns the newly calculated position.

```
move(self):
        ...
        future_position = position + self.direction
        self.epoch += 1
        return tuple(future_position)
```

In the Simulation class, within the next_epoch method, the move() method of the Ant class is called. The return value, which is the anticipated future position, is stored in a variable named future_position. This future_position is then checked using the newly implemented method check_future_position. If the coordinates are outside the set boundaries, check_future_position adjusts them to lie exactly on the boundary. Only after this adjustment is the new position assigned to Ant.coordinates.

```
 def next_epoch(self):
     for colony in self.colonies:
         for ant in colony.ants:
             self.update_pheromone(ant)
             future_position = ant.move()
             adjusted_position = self.check_future_position(future_position)
             ant.coordinates = adjusted_position
```

grafik




When the window size is changed using the 'Size' button, the boundary automatically and dynamically adjusts to the new size.

ezgif com-resize

**Comment by Jonah-gr** [comment]
To prevent the ants from permanently running into the edge, I have added that the direction is rotated by 180° with `ant.direction *= -1`.

**Comment by Jonah-gr** [comment]
Very good work @AlhaririAnas! Have you now implemented everything you wanted?

**Comment by AlhaririAnas** [comment]
@Jonah-gr, I don't think we need `ant.direction *= -1` because the ants should be allowed to move along the edge as they would in reality, instead of immediately changing their direction as soon as they reach the boundary.

So, when an ant reaches the boundary, it should autonomously decide which way to proceed from there, kind of 'randomly.' Do you see what I mean? 😅

**Comment by Jonah-gr** [comment]
Ah I see, that would probably be the most "natural" way. So if the ants are kept in too small a space with too high step size, they're likely to hang around the edge a lot. So good work! Then i will merge it now.

**Comment by Jonah-gr** [comment]
One more thing: why did you remove `self.epoch += 1` from the ant.move method within ìf self.epoch == 0:`? So self.epoch remains permanently at 0, right?

**Comment by AlhaririAnas** [comment]
@Jonah-gr Since `self.epoch` increments by one in each iteration (call) of the function, regardless of whether it's in the if or else block, it would be more efficient to move the increment of `self.epoch` to the end of the function (outside the if and else block). This way, self.epoch is uniformly and **only once** increased at the end of the function.

If there are any more questions or uncertainties, feel free to ask them. Otherwise, I have completed the development of this feature, and it can now be merged into the main branch. 😄

**Comment by Jonah-gr** [comment]
Ah, thank you. Now I have understood. Great job!

**Review by Jonah-gr — APPROVED** [review]

**Pull request merged**
