### PR TITLE
Added Devs folder and some content

### PR DESCRIPTION
**Pull request by honnigmelone**
Hey, first of all, sorry but I forgot to open an issue before. Florian send us a mail yesterday where it said: 

> Die Developer-Dokumentation sollte beschreiben, wie euer Code in etwa aufgebaut ist (mit einem Diagramm o.ä.), also welche Module/Klassen/wichtige Funktionen gibt es etc. Noch dazu sollten hier eure Algorithmen beschrieben werden.

Looking at our readme I feel like we have very extensive user documentation and a short devdoc. So we made it the other way around haha 😆 I thought it was a good idea to make a separate devs folder rather than adding more and more to rhe README. 

At the same time, I am not sure how and what we should describe for the architecture and algorithms. I am also not sure if we should keep it as a markdown. Important algorithms from my point of view would be how the ant moves (with and without pheromone influence) and maybe the pheromones but what else? Should the explanation be broad like right now or go into detail?
I left it broad for now to see what you guys say!
If you don't agree with some of the contents or the general idea feel free to change or discuss. The diagram should also be added here.

### CODE REVIEW

**Comment by Jonah-gr** [comment]
Good idea to put the developer documentation in its own folder! 

Unfortunately, this is not true, but it would still be a good implementation: **Obstacle Avoidance**: Ants detect and navigate around obstacles encountered during their search.

**Comment by heyitsalina** [comment]
nice work! looks more structured this way with the seperate devs folder

**Comment by honnigmelone** [comment]
I deleted the wrong sentence about obstacles now.

**Review by heyitsalina — APPROVED** [review]
looks good and you corrected the mistake jonah pointed out so i would just merge this :)

**Pull request merged**
