### PR TITLE
Move method for ant has been coded

### PR DESCRIPTION
**Pull request by AlhaririAnas**
I added two new attributes to the Ant class:

self.angle: This attribute represents the current angle of the ant.
self.step_size: This attribute sets the step size for the ant.

Regarding the move method:

This method doesn't return a value. Its purpose is to gradually and continuously update the attributes self.coordinates and self.angle until they reach the target coordinates (target_pos) and target angle (target_angle).
The parameters target_pos and target_angle can also be passed as random values to the move() method.

This design allows us to retrieve the current values for position and angle through the attributes (self.coordinates, self.angle). Therefore, we just need to call the move() method and access the attributes (self.coordinates, self.angle).

look at the photo:

current_pos represents self.coordiantes
current_angle represents self.angle

grafik

### CODE REVIEW

**Review by Jonah-gr — CHANGES_REQUESTED** [review]
Why did you use loops in the move method? Shouldn't the ant only move one step in the method? I would have rather thought that in the method the ant simply moves by a random value and angle (within a given range, of course). That's what I thought (feel free to improve, I'll have to rethink it, too):
1. at the beginning the ants have the same coordinates as the colony (x, y)
2. in the 0th epoch, random values $$(\bar{x}, \bar{y})_0$$ are determined with a fixed distance to the coordinates of the ant, but in any direction. These coordinates are added to the old ones: $$\text{Ant.coordinates} =(x, y) + (\bar{x}, \bar{y})_0 $$
3. in the next epoch, first determine a fixed range around the old step vector $$(\bar{x}, \bar{y})_{i-1}$$ to then determine a random point $$(\bar{x}, \bar{y})_i$$ in this range, which then becomes the new coordinates of the ant: $$\text{Ant.coordinates} =(x, y) + (\bar{x}, \bar{y})_i $$
4. repeat step 3
image

image
image

**Comment by AlhaririAnas** [comment]
@Jonah-gr I used While loops to gradually change the coordinates and angles until reaching the target values. With each change, the attributes (self.coordinate & self.angle) are updated, allowing the ant to move smoothly (for animated visualization). That was my initial idea, but I recognize that it may pose difficulties later, as you rightly pointed out.

I find your idea of using vector calculus reasonable, but there are still some uncertainties. I will reconsider this approach today, formulate possible questions, and leave them as comments....

**Comment by AlhaririAnas** [comment]
I have reconsidered your approach @Jonah-gr. Everything is clear for me so far, except for a few details

-"2. in the 0th epoch, random values $$(\bar{x}, \bar{y})_0$$ are determined with a fixed distance to the coordinates of the ant, but in any direction."
should we pass random values (destination coordinates) as parameter to the move() method?

-Should Ant.coordinates be a list of all visited coordinates, initialized as an empty list (self.coordinates = []), or should we handle this in the Simulation class?

-Is that how it works in Kivy? If you input start and destination coordinates, does the object (ant) smoothly move in real-time from start to the destination?

-Should the distance traveled by an ant to reach the next destination be uniform or within a random range? 
grafik


-Calculating the angle for an ant to rotate before walking towards its next destination: $$\angle(\mathbf{a}, \mathbf{b}) = \arccos\left(\frac{\mathbf{a} \odot \mathbf{b}}{\|\mathbf{a}\| \cdot \|\mathbf{b}\|}\right)$$
To calculate the angle between two vectors, I would define a new method called 'angle'.


Those are all the questions that have come up for now. I will recode the method as soon as possible.

**Comment by Jonah-gr** [comment]
1. "should we pass random values (destination coordinates) as parameter to the move() method?"  

I don't think the move method should be passed anything. I just thought that for each ant the move method is called and then an algorithm is started that overwrites the coordinates of that ant. Or do you think it would have advantages if we pass something to the move method?
In the very first step the ants go, I would let them move in a random direction. In all subsequent steps, the step then depends on the previous step.


2. "Should Ant.coordinates be a list of all visited coordinates, initialized as an empty list (self.coordinates = []), or should we handle this in the Simulation class?"

I think Ant.coordinates should simply be a tuple (x, y) and not a list. A list would probably reduce performance. We can think about how to handle the pheromones afterwards, but I don't think a list is necessary.


3. "Is that how it works in Kivy? If you input start and destination coordinates, does the object (ant) smoothly move in real-time from start to the destination?"

I would make the step size so small and the call simulation.next_epoch() in the gui so frequent that it almost looks like an animation and everything runs smoothly.


4. "Should the distance traveled by an ant to reach the nextdestination be uniform or within a random range?"

I think we should use a fixed but variable step size. This should simplify the whole thing but also makes sense that the ants always walk at the same speed.


You will certainly need more methods than just the move() method but I think the move() method should be the main method. Feel free to write as many methods as you need. But the move method should not be passed anything and should not return anything.

**Comment by AlhaririAnas** [comment]
I edited the Move method, following the discussed mathematical approach. The Move method does not return anything; it only calculates the new coordinates to which the ant should move, based on the previously visited coordinates.

The new coordinates to which an ant should move can be either randomly generated by setting the 'random' parameter to True or by specifying specific coordinates using the 'move_to' parameter.

Every visited coordinate is added to a list. _For example: Ant 1 Coordinates: [(5, 5), (15, 10), (23, 15)]_.
The initial coordinates (e.g., (5, 5)) correspond to the ant colony and should be passed to the new class parameter 'start_coordinate' when initializing a new object.

It is essential to track the ant's coordinates, whether in the Ant class or the Simulation class. Storing the ant's coordinates in the Ant class is advantageous for data encapsulation and centralized information management.

If you are not satisfied with my programming approach, feel free to edit or further develop the code.

**Comment by Jonah-gr** [comment]
I have more thought of something like that:

```python:
def move(self):
        position = np.array(self.coordinates)
       
        if self.epoch == 0:
            theta = np.random.uniform(0, 2 * np.pi)
            z = np.random.uniform(-1, 1)

            x = np.sqrt(1 - z**2) * np.cos(theta)
            y = np.sqrt(1 - z**2) * np.sin(theta)

            self.direction = np.array([x, y])

            position += self.direction
            self.coordinates = tuple(position)

            self.epoch += 1
        else:
            angle_offset = np.random.uniform(-np.pi/4, np.pi/4)

            rotation_matrix = np.array([[np.cos(angle_offset), -np.sin(angle_offset)],
                                        [np.sin(angle_offset), np.cos(angle_offset)]])
            self.direction = np.dot(rotation_matrix, self.direction)
            self.direction = self.direction / np.linalg.norm(self.direction)

            position += self.direction
            self.coordinates = tuple(position)

            self.epoch += 1
```
We can then add later how the direction changes depending on the perceived pheromones. This causes the ants to walk around randomly but in a range of +-45° around self.direction:
[Image from Gyazo](https://gyazo.com/0e4d5dc9a1eaff20fd8b53683370f809)
image

**Comment by AlhaririAnas** [comment]
@Jonah-gr I have adjusted the code. Thank you for your assistance. 😅

**Review by Jonah-gr — COMMENTED** [review]
I removed a few unnecessary args and used step_size in move() as well.

**Review by Jonah-gr — APPROVED** [review]

**Pull request merged**
