### PR TITLE
added obstacle feature

### PR DESCRIPTION
**Pull request by Jonah-gr**
You can now add obstacles to the simulation that the ants cannot walk over. The obstacles can be placed via a button, just like the colonies and food objects. At the moment an obstacle is always a rectangle with a fixed size, but we can change this later. 

The ants react to the obstacles in a similar way to the borders: If they want to run in, they are placed at the border of the obstacle.

The obstacles are also recorded in studies and can be loaded in again later.
I know that this is a bit ugly, but what do you think of the idea?

image

image

[Image from Gyazo](https://gyazo.com/9522c924e924e557133ca9d92e0767ec)

### CODE REVIEW

**Comment by Jonah-gr** [comment]
[Image from Gyazo](https://gyazo.com/9522c924e924e557133ca9d92e0767ec)

**Comment by tis22** [comment]
Crazy! 😯 
Maybe we need to update the explanation gif in the README now (if it's not too much of a hassle @AlhaririAnas).

**Comment by AlhaririAnas** [comment]
@tis22 It's a bit of a hassle, but no problem. I'll create a new explanatory GIF on February 20th.

**Comment by AlhaririAnas** [comment]
can we please use this image instead of square? @Jonah-gr 

lake

**Comment by Jonah-gr** [comment]
> can we please use this image instead of square? @Jonah-gr
> 
> lake

Sure, i can do it:)

**Comment by Jonah-gr** [comment]
Finished:)
image

**Comment by AlhaririAnas** [comment]
@Jonah-gr very nice .. thank you :)

**Comment by heyitsalina** [comment]
this is rly creative, wow well done!!

**Review by AlhaririAnas — APPROVED** [review]
Great job!

**Pull request merged**
